/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.*;
import models.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author eammn
 */
public class app_admin extends javax.swing.JFrame {

    /**
     * Creates new form app_admin
     */
    public app_admin() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_Panel = new javax.swing.JPanel();
        view_all_btn = new javax.swing.JButton();
        add_faculty_Button = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        feedback_btn = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        add_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        faculty_name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        department_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        courses_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        areaofexpertise_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        professionalInterest_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        search_Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        search_result_textarea = new javax.swing.JTextArea();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        edit_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        edit_professionalInterest_field = new javax.swing.JTextField();
        edit_areaofexpertise_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edit_courses_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edit_department_field = new javax.swing.JTextField();
        edit_faculty_name_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        feedback_panel = new javax.swing.JScrollPane();
        feedback_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        side_Panel.setBackground(new java.awt.Color(255, 255, 255));

        view_all_btn.setBackground(new java.awt.Color(0, 102, 204));
        view_all_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        view_all_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_all_btn.setText("view all");
        view_all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_btnActionPerformed(evt);
            }
        });

        add_faculty_Button.setBackground(new java.awt.Color(0, 102, 204));
        add_faculty_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_faculty_Button.setForeground(new java.awt.Color(255, 255, 255));
        add_faculty_Button.setText("add faculty");
        add_faculty_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_faculty_ButtonActionPerformed(evt);
            }
        });

        search_btn.setBackground(new java.awt.Color(0, 102, 204));
        search_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        logout_btn.setBackground(new java.awt.Color(0, 102, 204));
        logout_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        feedback_btn.setBackground(new java.awt.Color(0, 102, 204));
        feedback_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        feedback_btn.setForeground(new java.awt.Color(255, 255, 255));
        feedback_btn.setText("feedback");
        feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedback_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout side_PanelLayout = new javax.swing.GroupLayout(side_Panel);
        side_Panel.setLayout(side_PanelLayout);
        side_PanelLayout.setHorizontalGroup(
            side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_all_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_faculty_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(feedback_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        side_PanelLayout.setVerticalGroup(
            side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_PanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(view_all_btn)
                .addGap(77, 77, 77)
                .addComponent(add_faculty_Button)
                .addGap(68, 68, 68)
                .addComponent(search_btn)
                .addGap(37, 37, 37)
                .addComponent(feedback_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addGap(69, 69, 69))
        );

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new javax.swing.OverlayLayout(main_panel));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        main_panel.add(jScrollPane1);

        add_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("name");

        faculty_name_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("department");

        department_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("courses");

        courses_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("area of expertise");

        areaofexpertise_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("professional Interest");

        professionalInterest_field.setForeground(new java.awt.Color(0, 102, 204));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_panelLayout = new javax.swing.GroupLayout(add_panel);
        add_panel.setLayout(add_panelLayout);
        add_panelLayout.setHorizontalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_panelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jButton1))
                    .addGroup(add_panelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(faculty_name_field)
                            .addComponent(department_field)
                            .addComponent(courses_field)
                            .addComponent(areaofexpertise_field)
                            .addComponent(professionalInterest_field, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        add_panelLayout.setVerticalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(faculty_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(department_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(courses_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(areaofexpertise_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(professionalInterest_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        main_panel.add(add_panel);

        search_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("name");

        search_field.setForeground(new java.awt.Color(0, 102, 204));

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        search_result_textarea.setColumns(20);
        search_result_textarea.setRows(5);
        jScrollPane2.setViewportView(search_result_textarea);

        edit_btn.setBackground(new java.awt.Color(0, 102, 204));
        edit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setText("edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(204, 0, 0));
        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_PanelLayout = new javax.swing.GroupLayout(search_Panel);
        search_Panel.setLayout(search_PanelLayout);
        search_PanelLayout.setHorizontalGroup(
            search_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_PanelLayout.createSequentialGroup()
                .addGroup(search_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_PanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(edit_btn)
                        .addGap(47, 47, 47)
                        .addComponent(delete_btn))
                    .addGroup(search_PanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel6)
                        .addGap(100, 100, 100)
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        search_PanelLayout.setVerticalGroup(
            search_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_PanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(search_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(search_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(edit_btn)
                    .addComponent(delete_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        main_panel.add(search_Panel);

        edit_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("area of expertise");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("professional Interest");

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        edit_professionalInterest_field.setForeground(new java.awt.Color(0, 102, 204));

        edit_areaofexpertise_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("courses");

        edit_courses_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("department");

        edit_department_field.setForeground(new java.awt.Color(0, 102, 204));

        edit_faculty_name_field.setForeground(new java.awt.Color(0, 102, 204));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("name");

        javax.swing.GroupLayout edit_panelLayout = new javax.swing.GroupLayout(edit_panel);
        edit_panel.setLayout(edit_panelLayout);
        edit_panelLayout.setHorizontalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_panelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jButton3))
                    .addGroup(edit_panelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_faculty_name_field)
                            .addComponent(edit_department_field)
                            .addComponent(edit_courses_field)
                            .addComponent(edit_areaofexpertise_field)
                            .addComponent(edit_professionalInterest_field, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        edit_panelLayout.setVerticalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(edit_faculty_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(edit_department_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edit_courses_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edit_areaofexpertise_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(edit_professionalInterest_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        main_panel.add(edit_panel);

        feedback_area.setColumns(20);
        feedback_area.setRows(5);
        feedback_panel.setViewportView(feedback_area);

        main_panel.add(feedback_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_btnActionPerformed
        Faculty_controller fc = new Faculty_controller();
        ArrayList<Faculty> f = fc.get_all_faculties();
//        Label faculty_content = new Label();
//        faculty_content.setText("test");
//        content_panel.add(jLabel1);
        String data = new String();
        for (Faculty faculty : f) {
            data += "name: " + faculty.get_name()+ "\ndepartment: " + faculty.get_department()+ "\ncourses: " + faculty.get_courses()+ "\narea of expertise: " + faculty.get_areaofexpertise()+ "\nprofessional Interest: " + faculty.get_professionalInterest() + "\n\n";
        }
        jTextArea1.setText(data);
        jScrollPane1.setVisible(true);
        search_Panel.setVisible(false);
        add_panel.setVisible(false);
        feedback_area.setVisible(false);
        edit_panel.setVisible(false);
    }//GEN-LAST:event_view_all_btnActionPerformed

    private void add_faculty_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_faculty_ButtonActionPerformed
        jScrollPane1.setVisible(false);
        add_panel.setVisible(true);
        search_Panel.setVisible(false);
        edit_panel.setVisible(false);
        feedback_area.setVisible(false);

    }//GEN-LAST:event_add_faculty_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Faculty_controller fc = new Faculty_controller();
        String result = fc.add_faculty(faculty_name_field.getText(), department_field.getText(), courses_field.getText(), areaofexpertise_field.getText(), professionalInterest_field.getText());
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        search_Panel.setVisible(true);
        add_panel.setVisible(false);
        edit_panel.setVisible(false);
        feedback_area.setVisible(false);
        search_result_textarea.setText("");
        search_field.setText("");
    }//GEN-LAST:event_search_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        search_result_textarea.setText("");
//        Faculty_controller fc = new Faculty_controller();
//        Faculty faculty;
 
        AbstractFaculty faculty = faculty_factory.get_faculty(search_field.getText());
        if (faculty.isNil()) {
            JOptionPane.showMessageDialog(null, "not found");
        } else {
            search_result_textarea.setText("name: " + faculty.get_name()+ "\ndepartment: " + faculty.get_department()+ "\ncourses: " + faculty.get_courses()+ "\narea of expertise: " + faculty.get_areaofexpertise()+ "\nprofessional Interest: " + faculty.get_professionalInterest());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    Faculty fac = null;
    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        Faculty_controller fc = new Faculty_controller();
        fac = fc.get_faculty(search_field.getText());
        if (fac == null) {
            JOptionPane.showMessageDialog(null, "not found");
        } else {
            edit_areaofexpertise_field.setText(fac.get_areaofexpertise());
            edit_courses_field.setText(fac.get_courses());
            edit_department_field.setText(fac.get_department());
            edit_faculty_name_field.setText(fac.get_name());
            edit_professionalInterest_field.setText(fac.get_professionalInterest());
            jScrollPane1.setVisible(false);
            search_Panel.setVisible(false);
            add_panel.setVisible(false);
            edit_panel.setVisible(true);
            feedback_area.setVisible(false);
            search_result_textarea.setText("");

        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        Faculty_controller fc = new Faculty_controller();
        String result = fc.delete_faculty(search_field.getText());
        JOptionPane.showMessageDialog(null, result);
        search_result_textarea.setText("");
        search_field.setText("");
    }//GEN-LAST:event_delete_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Faculty_controller fc = new Faculty_controller();
        String result = fc.edit_faculty(edit_faculty_name_field.getText(), edit_department_field.getText(), edit_courses_field.getText(), edit_areaofexpertise_field.getText(), edit_professionalInterest_field.getText());
        JOptionPane.showMessageDialog(null, result);
        jScrollPane1.setVisible(false);
        search_Panel.setVisible(true);
        add_panel.setVisible(false);
        edit_panel.setVisible(false);
        feedback_area.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        login_view a = new login_view();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedback_btnActionPerformed
        Feedback_controller fc=new Feedback_controller();
        ArrayList<Feedback> feed = new ArrayList<>();
        feed=fc.view_feedback();
        String result="";
        for (Feedback feedback : feed) {
            result+="name: "+feedback.getName()+"\n\nSubject: "+feedback.getSubject()+"\n\nMessage: "+feedback.getMessage()+"\n\n\n";
        }
        System.out.println(result);
        feedback_area.setText(result);
        jScrollPane1.setVisible(false);
        add_panel.setVisible(false);
        search_Panel.setVisible(false);
        edit_panel.setVisible(false);
        feedback_area.setVisible(true);
    }//GEN-LAST:event_feedback_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_faculty_Button;
    private javax.swing.JPanel add_panel;
    private javax.swing.JTextField areaofexpertise_field;
    private javax.swing.JTextField courses_field;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField department_field;
    private javax.swing.JTextField edit_areaofexpertise_field;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField edit_courses_field;
    private javax.swing.JTextField edit_department_field;
    private javax.swing.JTextField edit_faculty_name_field;
    private javax.swing.JPanel edit_panel;
    private javax.swing.JTextField edit_professionalInterest_field;
    private javax.swing.JTextField faculty_name_field;
    private javax.swing.JTextArea feedback_area;
    private javax.swing.JButton feedback_btn;
    private javax.swing.JScrollPane feedback_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField professionalInterest_field;
    private javax.swing.JPanel search_Panel;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_field;
    private javax.swing.JTextArea search_result_textarea;
    private javax.swing.JPanel side_Panel;
    private javax.swing.JButton view_all_btn;
    // End of variables declaration//GEN-END:variables
}
