/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.Faculty_controller;
import controllers.Feedback_controller;
import controllers.faculty_factory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.AbstractFaculty;
import models.Faculty;

/**
 *
 * @author eammn
 */
public class app_user extends javax.swing.JFrame {

    /**
     * Creates new form app_user
     */
    public app_user() {
        initComponents();
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_Panel = new javax.swing.JPanel();
        view_all_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        add_feedback_btn = new javax.swing.JButton();
        back_to_login_btn = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_faculty_TextArea = new javax.swing.JTextArea();
        search_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        search_result_textarea = new javax.swing.JTextArea();
        add_feedback_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        subject_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        message_field = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        side_Panel.setBackground(new java.awt.Color(255, 255, 255));
        side_Panel.setPreferredSize(new java.awt.Dimension(162, 496));

        view_all_btn.setBackground(new java.awt.Color(0, 102, 204));
        view_all_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        view_all_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_all_btn.setText("view all");
        view_all_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_btnActionPerformed(evt);
            }
        });

        search_btn.setBackground(new java.awt.Color(0, 102, 204));
        search_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        add_feedback_btn.setBackground(new java.awt.Color(0, 102, 204));
        add_feedback_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_feedback_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_feedback_btn.setText("send feedback");
        add_feedback_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_feedback_btnActionPerformed(evt);
            }
        });

        back_to_login_btn.setBackground(new java.awt.Color(0, 102, 204));
        back_to_login_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back_to_login_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_to_login_btn.setText("back");
        back_to_login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout side_PanelLayout = new javax.swing.GroupLayout(side_Panel);
        side_Panel.setLayout(side_PanelLayout);
        side_PanelLayout.setHorizontalGroup(
            side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_all_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_feedback_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_to_login_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        side_PanelLayout.setVerticalGroup(
            side_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_PanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(view_all_btn)
                .addGap(81, 81, 81)
                .addComponent(search_btn)
                .addGap(86, 86, 86)
                .addComponent(add_feedback_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_to_login_btn)
                .addGap(64, 64, 64))
        );

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setLayout(new javax.swing.OverlayLayout(main_panel));

        view_faculty_TextArea.setColumns(20);
        view_faculty_TextArea.setRows(5);
        jScrollPane1.setViewportView(view_faculty_TextArea);

        main_panel.add(jScrollPane1);

        search_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("name");

        search_field.setForeground(new java.awt.Color(0, 102, 204));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        search_result_textarea.setColumns(20);
        search_result_textarea.setRows(5);
        jScrollPane2.setViewportView(search_result_textarea);

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel6)
                        .addGap(100, 100, 100)
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton3)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        main_panel.add(search_panel);

        add_feedback_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("email");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("subject");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("message");

        jButton5.setBackground(new java.awt.Color(0, 102, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("send");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_feedback_panelLayout = new javax.swing.GroupLayout(add_feedback_panel);
        add_feedback_panel.setLayout(add_feedback_panelLayout);
        add_feedback_panelLayout.setHorizontalGroup(
            add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_feedback_panelLayout.createSequentialGroup()
                .addGroup(add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_feedback_panelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(116, 116, 116)
                        .addGroup(add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email_field)
                            .addComponent(subject_field)
                            .addComponent(message_field, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(add_feedback_panelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jButton5)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        add_feedback_panelLayout.setVerticalGroup(
            add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_feedback_panelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subject_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(add_feedback_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(message_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton5)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        main_panel.add(add_feedback_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_all_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_btnActionPerformed
        Faculty_controller fc = new Faculty_controller();
        ArrayList<Faculty> f = fc.get_all_faculties();
        String data = new String();
        for (Faculty faculty : f) {
            data += "name: " + faculty.get_name()+ "\ndepartment: " + faculty.get_department()+ "\ncourses: " + faculty.get_courses()+ "\narea of expertise: " + faculty.get_areaofexpertise()+ "\nprofessional Interest: " + faculty.get_professionalInterest() + "\n\n";
        }
        view_faculty_TextArea.setText(data);
        jScrollPane1.setVisible(true);
        search_panel.setVisible(false);
        add_feedback_panel.setVisible(false);

    }//GEN-LAST:event_view_all_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        jScrollPane1.setVisible(false);
        search_panel.setVisible(true);
        add_feedback_panel.setVisible(false);
    }//GEN-LAST:event_search_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        search_result_textarea.setText("");
//        Faculty_controller fc = new Faculty_controller();
//        Faculty faculty;
        AbstractFaculty faculty = new faculty_factory().get_faculty(search_field.getText());
        if (faculty.isNil()) {
            JOptionPane.showMessageDialog(null, "not found");
        } else {
            search_result_textarea.setText("name: " + faculty.get_name()+ "\ndepartment: " + faculty.get_department()+ "\ncourses: " + faculty.get_courses()+ "\narea of expertise: " + faculty.get_areaofexpertise()+ "\nprofessional Interest: " + faculty.get_professionalInterest());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Feedback_controller fc = new Feedback_controller();
        String result = fc.add_feedback(email_field.getText(), subject_field.getText(), message_field.getText());
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void add_feedback_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_feedback_btnActionPerformed
        jScrollPane1.setVisible(false);
        search_panel.setVisible(false);
        add_feedback_panel.setVisible(true);
    }//GEN-LAST:event_add_feedback_btnActionPerformed

    private void back_to_login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_login_btnActionPerformed
        login_view a = new login_view();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_to_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_feedback_btn;
    private javax.swing.JPanel add_feedback_panel;
    private javax.swing.JButton back_to_login_btn;
    private javax.swing.JTextField email_field;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField message_field;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTextArea search_result_textarea;
    private javax.swing.JPanel side_Panel;
    private javax.swing.JTextField subject_field;
    private javax.swing.JButton view_all_btn;
    private javax.swing.JTextArea view_faculty_TextArea;
    // End of variables declaration//GEN-END:variables
}
